// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.0
// - protoc             v3.21.12
// source: devicehub/devicehub.proto

package devicehub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessService_CoPost_FullMethodName      = "/devicehub.AccessService/CoPost"
	AccessService_ObGet_FullMethodName       = "/devicehub.AccessService/ObGet"
	AccessService_DeviceQuery_FullMethodName = "/devicehub.AccessService/DeviceQuery"
)

// AccessServiceClient is the client API for AccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessServiceClient interface {
	CoPost(ctx context.Context, in *CoReq, opts ...grpc.CallOption) (*CoResp, error)
	ObGet(ctx context.Context, in *ObGetReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObGetResp], error)
	DeviceQuery(ctx context.Context, in *DeviceQueryReq, opts ...grpc.CallOption) (*DeviceQueryResp, error)
}

type accessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessServiceClient(cc grpc.ClientConnInterface) AccessServiceClient {
	return &accessServiceClient{cc}
}

func (c *accessServiceClient) CoPost(ctx context.Context, in *CoReq, opts ...grpc.CallOption) (*CoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoResp)
	err := c.cc.Invoke(ctx, AccessService_CoPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) ObGet(ctx context.Context, in *ObGetReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObGetResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccessService_ServiceDesc.Streams[0], AccessService_ObGet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObGetReq, ObGetResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccessService_ObGetClient = grpc.ServerStreamingClient[ObGetResp]

func (c *accessServiceClient) DeviceQuery(ctx context.Context, in *DeviceQueryReq, opts ...grpc.CallOption) (*DeviceQueryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceQueryResp)
	err := c.cc.Invoke(ctx, AccessService_DeviceQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServiceServer is the server API for AccessService service.
// All implementations must embed UnimplementedAccessServiceServer
// for forward compatibility.
type AccessServiceServer interface {
	CoPost(context.Context, *CoReq) (*CoResp, error)
	ObGet(*ObGetReq, grpc.ServerStreamingServer[ObGetResp]) error
	DeviceQuery(context.Context, *DeviceQueryReq) (*DeviceQueryResp, error)
	mustEmbedUnimplementedAccessServiceServer()
}

// UnimplementedAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessServiceServer struct{}

func (UnimplementedAccessServiceServer) CoPost(context.Context, *CoReq) (*CoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoPost not implemented")
}
func (UnimplementedAccessServiceServer) ObGet(*ObGetReq, grpc.ServerStreamingServer[ObGetResp]) error {
	return status.Errorf(codes.Unimplemented, "method ObGet not implemented")
}
func (UnimplementedAccessServiceServer) DeviceQuery(context.Context, *DeviceQueryReq) (*DeviceQueryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceQuery not implemented")
}
func (UnimplementedAccessServiceServer) mustEmbedUnimplementedAccessServiceServer() {}
func (UnimplementedAccessServiceServer) testEmbeddedByValue()                       {}

// UnsafeAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessServiceServer will
// result in compilation errors.
type UnsafeAccessServiceServer interface {
	mustEmbedUnimplementedAccessServiceServer()
}

func RegisterAccessServiceServer(s grpc.ServiceRegistrar, srv AccessServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessService_ServiceDesc, srv)
}

func _AccessService_CoPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CoPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CoPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CoPost(ctx, req.(*CoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_ObGet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObGetReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccessServiceServer).ObGet(m, &grpc.GenericServerStream[ObGetReq, ObGetResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccessService_ObGetServer = grpc.ServerStreamingServer[ObGetResp]

func _AccessService_DeviceQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).DeviceQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_DeviceQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).DeviceQuery(ctx, req.(*DeviceQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessService_ServiceDesc is the grpc.ServiceDesc for AccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicehub.AccessService",
	HandlerType: (*AccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CoPost",
			Handler:    _AccessService_CoPost_Handler,
		},
		{
			MethodName: "DeviceQuery",
			Handler:    _AccessService_DeviceQuery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ObGet",
			Handler:       _AccessService_ObGet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "devicehub/devicehub.proto",
}
