// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: devicehub/devicehub.proto

package devicehub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_CODE_INTERNAL_SERVER_ERROR Code = 0
	Code_CODE_OK                    Code = 1
	Code_CODE_DEVICEID_OFFLINE      Code = 2
	Code_CODE_DEVICEID_TIMEOUT      Code = 3
	Code_CODE_CONTINUE              Code = 4
	Code_CODE_TERMINATE             Code = 5
	Code_CODE_NOT_FOUNT             Code = 6
	Code_CODE_BAD_REQUEST           Code = 7
	Code_CODE_METHOD_NOT_ALLOWED    Code = 8
	Code_CODE_TOO_MANY_REQUESTS     Code = 9
	Code_CODE_TOO_MANY_OBSERVERS    Code = 10
	Code_CODE_REQUEST_TIMEOUT       Code = 11
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "CODE_INTERNAL_SERVER_ERROR",
		1:  "CODE_OK",
		2:  "CODE_DEVICEID_OFFLINE",
		3:  "CODE_DEVICEID_TIMEOUT",
		4:  "CODE_CONTINUE",
		5:  "CODE_TERMINATE",
		6:  "CODE_NOT_FOUNT",
		7:  "CODE_BAD_REQUEST",
		8:  "CODE_METHOD_NOT_ALLOWED",
		9:  "CODE_TOO_MANY_REQUESTS",
		10: "CODE_TOO_MANY_OBSERVERS",
		11: "CODE_REQUEST_TIMEOUT",
	}
	Code_value = map[string]int32{
		"CODE_INTERNAL_SERVER_ERROR": 0,
		"CODE_OK":                    1,
		"CODE_DEVICEID_OFFLINE":      2,
		"CODE_DEVICEID_TIMEOUT":      3,
		"CODE_CONTINUE":              4,
		"CODE_TERMINATE":             5,
		"CODE_NOT_FOUNT":             6,
		"CODE_BAD_REQUEST":           7,
		"CODE_METHOD_NOT_ALLOWED":    8,
		"CODE_TOO_MANY_REQUESTS":     9,
		"CODE_TOO_MANY_OBSERVERS":    10,
		"CODE_REQUEST_TIMEOUT":       11,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_devicehub_devicehub_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_devicehub_devicehub_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_devicehub_devicehub_proto_rawDescGZIP(), []int{0}
}

type CoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Uri      string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Data     []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CoReq) Reset() {
	*x = CoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicehub_devicehub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoReq) ProtoMessage() {}

func (x *CoReq) ProtoReflect() protoreflect.Message {
	mi := &file_devicehub_devicehub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoReq.ProtoReflect.Descriptor instead.
func (*CoReq) Descriptor() ([]byte, []int) {
	return file_devicehub_devicehub_proto_rawDescGZIP(), []int{0}
}

func (x *CoReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CoReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CoReq) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *CoReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code Code   `protobuf:"varint,2,opt,name=code,proto3,enum=devicehub.Code" json:"code,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CoResp) Reset() {
	*x = CoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicehub_devicehub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoResp) ProtoMessage() {}

func (x *CoResp) ProtoReflect() protoreflect.Message {
	mi := &file_devicehub_devicehub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoResp.ProtoReflect.Descriptor instead.
func (*CoResp) Descriptor() ([]byte, []int) {
	return file_devicehub_devicehub_proto_rawDescGZIP(), []int{1}
}

func (x *CoResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CoResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_INTERNAL_SERVER_ERROR
}

func (x *CoResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ObGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Uri      string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Data     []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ObGetReq) Reset() {
	*x = ObGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicehub_devicehub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObGetReq) ProtoMessage() {}

func (x *ObGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_devicehub_devicehub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObGetReq.ProtoReflect.Descriptor instead.
func (*ObGetReq) Descriptor() ([]byte, []int) {
	return file_devicehub_devicehub_proto_rawDescGZIP(), []int{2}
}

func (x *ObGetReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ObGetReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ObGetReq) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ObGetReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ObGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fid  uint32 `protobuf:"varint,2,opt,name=fid,proto3" json:"fid,omitempty"` // frame id
	Code Code   `protobuf:"varint,3,opt,name=code,proto3,enum=devicehub.Code" json:"code,omitempty"`
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ObGetResp) Reset() {
	*x = ObGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicehub_devicehub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObGetResp) ProtoMessage() {}

func (x *ObGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_devicehub_devicehub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObGetResp.ProtoReflect.Descriptor instead.
func (*ObGetResp) Descriptor() ([]byte, []int) {
	return file_devicehub_devicehub_proto_rawDescGZIP(), []int{3}
}

func (x *ObGetResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ObGetResp) GetFid() uint32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *ObGetResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_INTERNAL_SERVER_ERROR
}

func (x *ObGetResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeviceQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (x *DeviceQueryReq) Reset() {
	*x = DeviceQueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicehub_devicehub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceQueryReq) ProtoMessage() {}

func (x *DeviceQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_devicehub_devicehub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceQueryReq.ProtoReflect.Descriptor instead.
func (*DeviceQueryReq) Descriptor() ([]byte, []int) {
	return file_devicehub_devicehub_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceQueryReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceQueryReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeviceQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code        Code   `protobuf:"varint,2,opt,name=code,proto3,enum=devicehub.Code" json:"code,omitempty"`
	BodyCapSize uint32 `protobuf:"varint,3,opt,name=body_cap_size,json=bodyCapSize,proto3" json:"body_cap_size,omitempty"`
	RemoteAddr  string `protobuf:"bytes,4,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
}

func (x *DeviceQueryResp) Reset() {
	*x = DeviceQueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devicehub_devicehub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceQueryResp) ProtoMessage() {}

func (x *DeviceQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_devicehub_devicehub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceQueryResp.ProtoReflect.Descriptor instead.
func (*DeviceQueryResp) Descriptor() ([]byte, []int) {
	return file_devicehub_devicehub_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceQueryResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceQueryResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_INTERNAL_SERVER_ERROR
}

func (x *DeviceQueryResp) GetBodyCapSize() uint32 {
	if x != nil {
		return x.BodyCapSize
	}
	return 0
}

func (x *DeviceQueryResp) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

var File_devicehub_devicehub_proto protoreflect.FileDescriptor

var file_devicehub_devicehub_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2f, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x22, 0x5a, 0x0a, 0x05, 0x43, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x51, 0x0a, 0x06, 0x43, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x08, 0x4f, 0x62, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a, 0x09, 0x4f, 0x62, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x66, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x0e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x0f,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x23, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x63, 0x61, 0x70,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x62, 0x6f, 0x64,
	0x79, 0x43, 0x61, 0x70, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x2a, 0xaa, 0x02, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12,
	0x19, 0x0a, 0x15, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x49, 0x44,
	0x5f, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x49, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45,
	0x4f, 0x55, 0x54, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x06,
	0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x10, 0x07, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4d,
	0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x45,
	0x44, 0x10, 0x08, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x5f,
	0x4d, 0x41, 0x4e, 0x59, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x53, 0x10, 0x09, 0x12,
	0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x5f, 0x4d, 0x41, 0x4e, 0x59,
	0x5f, 0x4f, 0x42, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x53, 0x10, 0x0a, 0x12, 0x18, 0x0a, 0x14,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54, 0x49, 0x4d,
	0x45, 0x4f, 0x55, 0x54, 0x10, 0x0b, 0x32, 0xc0, 0x01, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x43, 0x6f, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x10, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x43,
	0x6f, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62,
	0x2e, 0x43, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x05, 0x4f, 0x62, 0x47,
	0x65, 0x74, 0x12, 0x13, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x4f,
	0x62, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x68, 0x75, 0x62, 0x2e, 0x4f, 0x62, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x19, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6b, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f,
	0x77, 0x2f, 0x72, 0x74, 0x69, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_devicehub_devicehub_proto_rawDescOnce sync.Once
	file_devicehub_devicehub_proto_rawDescData = file_devicehub_devicehub_proto_rawDesc
)

func file_devicehub_devicehub_proto_rawDescGZIP() []byte {
	file_devicehub_devicehub_proto_rawDescOnce.Do(func() {
		file_devicehub_devicehub_proto_rawDescData = protoimpl.X.CompressGZIP(file_devicehub_devicehub_proto_rawDescData)
	})
	return file_devicehub_devicehub_proto_rawDescData
}

var file_devicehub_devicehub_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_devicehub_devicehub_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_devicehub_devicehub_proto_goTypes = []interface{}{
	(Code)(0),               // 0: devicehub.Code
	(*CoReq)(nil),           // 1: devicehub.CoReq
	(*CoResp)(nil),          // 2: devicehub.CoResp
	(*ObGetReq)(nil),        // 3: devicehub.ObGetReq
	(*ObGetResp)(nil),       // 4: devicehub.ObGetResp
	(*DeviceQueryReq)(nil),  // 5: devicehub.DeviceQueryReq
	(*DeviceQueryResp)(nil), // 6: devicehub.DeviceQueryResp
}
var file_devicehub_devicehub_proto_depIdxs = []int32{
	0, // 0: devicehub.CoResp.code:type_name -> devicehub.Code
	0, // 1: devicehub.ObGetResp.code:type_name -> devicehub.Code
	0, // 2: devicehub.DeviceQueryResp.code:type_name -> devicehub.Code
	1, // 3: devicehub.AccessService.CoPost:input_type -> devicehub.CoReq
	3, // 4: devicehub.AccessService.ObGet:input_type -> devicehub.ObGetReq
	5, // 5: devicehub.AccessService.DeviceQuery:input_type -> devicehub.DeviceQueryReq
	2, // 6: devicehub.AccessService.CoPost:output_type -> devicehub.CoResp
	4, // 7: devicehub.AccessService.ObGet:output_type -> devicehub.ObGetResp
	6, // 8: devicehub.AccessService.DeviceQuery:output_type -> devicehub.DeviceQueryResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_devicehub_devicehub_proto_init() }
func file_devicehub_devicehub_proto_init() {
	if File_devicehub_devicehub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_devicehub_devicehub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicehub_devicehub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicehub_devicehub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicehub_devicehub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicehub_devicehub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceQueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devicehub_devicehub_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceQueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_devicehub_devicehub_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devicehub_devicehub_proto_goTypes,
		DependencyIndexes: file_devicehub_devicehub_proto_depIdxs,
		EnumInfos:         file_devicehub_devicehub_proto_enumTypes,
		MessageInfos:      file_devicehub_devicehub_proto_msgTypes,
	}.Build()
	File_devicehub_devicehub_proto = out.File
	file_devicehub_devicehub_proto_rawDesc = nil
	file_devicehub_devicehub_proto_goTypes = nil
	file_devicehub_devicehub_proto_depIdxs = nil
}
